services:
  db:
    image: postgres
    container_name: db-telegram-nest-bas
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - webnet

  bot:
    build:
      context: .  # Використовуємо кореневу директорію
      dockerfile: bot/Dockerfile
    container_name: bot-telegram-nest-bas
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TOKEN: ${TOKEN}
      WEBHOOK_URL: ${DOMAIN}
      PORT: ${PORT}
    expose:
      - "3000"
    networks:
      - webnet
    depends_on:
      - db

volumes:
  db-data:

networks:
  webnet:
    external: true
